name:                datafeeds
version:             0.1.0.0
github:              "githubuser/datafeeds"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/datafeeds#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- criterion
- configurator
- filepath
- directory
- hashable
- hashtables
- http-client
- http-conduit
- http-types
- hedgehog
- tasty-hedgehog
- aeson
- websockets
- bytestring
- text
- wuss >= 1.1 
- streaming
- safe-exceptions
- scientific
- async
- store
- snap-core
- snap-server
- websockets-snap
- time
- random
- mtl
- streaming-bytestring
- zlib
- zstd
- cryptonite
- memory
- unix
- uuid
- th-utilities
- unordered-containers
- vector

library:
  source-dirs: src

executables:
  proclog :
    main:                Main.hs
    source-dirs:         app/logger
    ghc-options:
    - -threaded
    - -Wall
    - -O2
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - datafeeds

  feedlogger:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -Wall
    - -O2
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - datafeeds

tests:
  unittests-feedlogger:
    main:                Spec.hs
    source-dirs:         tests
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - datafeeds
